# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Info Center for League of Legends' do
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
	workspace 'project'
	
	# Pods for Info Center for League of Legends
	pod 'BEMSimpleLineGraph', :git => 'https://github.com/Boris-Em/BEMSimpleLineGraph.git', :branch => 'feature'
	pod 'MBCircularProgressBar'
	pod 'SGSStaggeredFlowLayout'
	pod 'XCDYouTubeKit'
	pod 'AMPopTip'
	pod 'JSBadgeView'
end
